### ISSUE TITLE
This crate uses a feature that was deprecated 2020-04-10 and therefore does not compile anymore

### ISSUE THREAD

**Issue by saethlin** [kmcallister/syscall.rs#32]
https://github.com/rust-lang/rust/pull/71007

**Comment by houqp** [comment]
fixed by https://github.com/kmcallister/syscall.rs/pull/33, but looks like this project is not being maintained anymore :(

**Comment by milahu** [comment]
[install rust dependency from github](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories)

```toml
# Cargo.toml
[dependencies]
#syscall = "*"
syscall = { git = "https://github.com/aaronjeline/syscall.rs" }
```

llvm_asm requires rust nightly

```toml
# rust-toolchain.toml
[toolchain]
channel = "nightly-2021-09-28"
```

```
cargo +nightly build
```
